;===============================================================================
; ASTERISK MANAGER INTERFACE (AMI) KONFIGURATSIYA
; Autodialer Python skripti uchun
;===============================================================================

[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0
displayconnects = yes
timestampevents = yes

;-------------------------------------------------------------------------------
; AUTODIALER FOYDALANUVCHI
;-------------------------------------------------------------------------------
[autodialer]
secret = autodialer123
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
permit = 172.16.0.0/255.240.0.0
permit = 10.0.0.0/255.0.0.0
permit = 192.168.0.0/255.255.0.0
read = system,call,log,verbose,command,agent,user,originate
write = system,call,log,verbose,command,agent,user,originate
writetimeout = 5000
